# Generated by Django 4.2.11 on 2024-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('executor', models.CharField(max_length=50)),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
